services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "pem migrate && uvicorn src.main:app --host 0.0.0.0 --port 8080 --reload"
    env_file:
      - ./src/.env
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./src/app:/code/app
      - ./src/.env:/code/.env
  db:
    image: postgres:13
    env_file:
      - ./src/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5555:5432"

volumes:
  postgres-data:
